
# Simple workflow for deploying static content to GitHub Pages
name: BUild file
jobs:
  # Single deploy job since we're just deploying
  deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            tcu_spec/main.tex
          work_in_root_file_dir: true
