
# Simple workflow for deploying static content to GitHub Pages
name: BUild file
on:
  push:
    branches:
      - "*"
  
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        name: Build
        with:
          root_file: |
            spec/main.tex
          work_in_root_file_dir: true
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.2.0
        with:
          path: spec/main.pdf
